fix: release workflow
cisagov/con-pca-tasks pull request #7
Opened 2023-02-03 00:33 UTC by itsmostafa

fix inconsistencies in the matrix build to avoid binaries failing to run in github actions.

## 🗣 Description ##
removed the unused `os` var in the matrix
removed the duplicate `bins` outside of includes

## 💭 Motivation and context ##

## 🧪 Testing ##

will be testing when this PR is merged as binaries successfully run on 
my local machine

## ✅ Pre-approval checklist ##

- [x] This PR has an informative and human-readable title.
- [x] Changes are limited to a single goal - *eschew scope creep!*
- [x] I have read the [CONTRIBUTING](../blob/develop/CONTRIBUTING.md) document.
- [x] These code changes follow [cisagov code standards](https://github.com/cisagov/development-guide).
- [x] All relevant repo and/or project documentation has been updated
      to reflect the changes in this PR.
- [x] All new and existing tests pass.

## ✅ Pre-merge checklist ##

- [ ] Revert dependencies to default branches.
- [ ] Finalize version.

## ✅ Post-merge checklist ##

- [ ] Add a tag or create a release.

2023-02-03 07:10 UTC, mcdonnnj requested changes

2023-02-03 07:10 UTC, mcdonnnj commented on .github/workflows/release.yml
>      runs-on: ubuntu-latest
I cannot throw a suggestion in here because it includes an out of range line but I think something like this would be a better approach:

```yaml
    name: go-build ${{ matrix.goos }}-${{ matrix.arch }}
```

This should provide a more useful name in the GitHub UI.

2023-02-03 07:10 UTC, mcdonnnj commented on .github/workflows/release.yml
>              arch: amd64
Please sort all of the `include` entries alphabetically by their keys:

```suggestion
          - arch: amd64
            bin: pca-linux-amd64
            goos: linux
```

I cannot do one full suggestion because the last two entries are out of range.

2023-02-03 16:19 UTC, itsmostafa commented on .github/workflows/release.yml
>              arch: amd64
@mcdonnnj resolved with [bd30707](https://github.com/cisagov/con-pca-tasks/pull/7/commits/bd307077587166fe82227e78768b6f23b34d15ac)

2023-02-03 16:19 UTC, itsmostafa commented on .github/workflows/release.yml
>      runs-on: ubuntu-latest
@mcdonnnj resolved with [bd30707](https://github.com/cisagov/con-pca-tasks/pull/7/commits/bd307077587166fe82227e78768b6f23b34d15ac)

2023-02-07 15:52 UTC, mcdonnnj requested changes
This is all looking pretty good. I have some small suggestions for your consideration.

2023-02-07 15:52 UTC, mcdonnnj commented on .github/workflows/release.yml
> +          echo "VERSION=v$(./bin/pca-linux-amd64/pca-linux-amd64 -version)" \
Would you make the `pca-linux-amd64` value an `env` for the workflow? I'd prefer to have this be configurable instead of hard coded.

2023-02-07 15:52 UTC, mcdonnnj commented on .github/workflows/release.yml
> +
Nit-picky but do these empty lines need to be here?

2023-02-07 15:52 UTC, mcdonnnj commented on .github/workflows/release.yml
> +      - name: chmod executable
Just something more natural English and explanatory.

```suggestion
      - name: Make retrieved artifact executable
```

2023-02-07 16:22 UTC, itsmostafa commented on .github/workflows/release.yml
> +      - name: chmod executable
@mcdonnnj resolved with [d90443c](https://github.com/cisagov/con-pca-tasks/pull/7/commits/d90443c9a8faafafa6ce2c5ffeb009a7f3ef34c5)

2023-02-07 16:22 UTC, itsmostafa commented on .github/workflows/release.yml
> +
@mcdonnnj resolved with [d90443c](https://github.com/cisagov/con-pca-tasks/pull/7/commits/d90443c9a8faafafa6ce2c5ffeb009a7f3ef34c5)

2023-02-07 18:25 UTC, itsmostafa commented on .github/workflows/release.yml
> +          echo "VERSION=v$(./bin/pca-linux-amd64/pca-linux-amd64 -version)" \
@mcdonnnj resolved with [a3b255b](https://github.com/cisagov/con-pca-tasks/pull/7/commits/a3b255b957165628f6f3201cdf7f0dcc3993a4a3)

2023-02-08 20:12 UTC, mcdonnnj commented on .github/workflows/release.yml
> +          echo "VERSION=v$(./bin/pca-linux-amd64/pca-linux-amd64 -version)" \
Change is in https://github.com/cisagov/con-pca-tasks/pull/7/commits/bc9359ad0942237bf05421e3334006c3404fe2eb for posterity.

2023-02-09 08:55 UTC, mcdonnnj approved these changes
Seems reasonable enough ✔

2023-02-09 16:24 UTC, izzy64 approved these changes
LGTM

2023-02-09 16:25 UTC, merged